apiVersion: v1
kind: Service
metadata:
  name: snakejs-service
spec:
  selector:
    app: snakejs
  ports:
  - protocol: "TCP"
    port: 31234
    targetPort: 80
  type: LoadBalancer
  externalIPs:
  - 172.31.30.100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakejs
spec:
  selector:
    matchLabels:
      app: snakejs
  replicas: 2
  template:
    metadata:
      labels:
        app: snakejs
    spec:
      containers:
      - name: snakejs
        image: itaibenyishai/snakejs:latest
        ports:
        - containerPort: 80
